[tool.poetry]
name = "terminally_ASPIRED"
version = "0.1.0"
description = "CLI for spectral reduction for the SAAO 74 inch using ASPIRED backend"
authors = ["Francois Campher"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS independant",
]
license-files = ["LICEN[CS]E*"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"

asdf = "4.1.0"
asdf-astropy = "0.7.1"
asdf-coordinates-schemas = "0.3.0"
asdf-standard = "1.1.1"
asdf-transform-schemas = "0.5.0"
asdf-wcs-schemas = "0.4.0"
astropy = "7.0.1"
astropy-healpix = "1.1.2"
astropy-iers-data = "0.2025.3.24.0.35.32"
astroscrappy = "1.2.0"
attrs = "25.3.0"
ccdproc = "2.4.3"
click = "8.1.8"
cloudpickle = "3.1.1"
crc32c = "2.7.1"
dask = "2025.3.0"
deprecated = "1.2.18"
donfig = "0.8.1.post1"
fsspec = "2025.3.2"
gwcs = "0.24.0"
imageio = "2.37.0"
importlib-metadata = "8.6.1"
jmespath = "1.0.1"
kaleido = "0.2.1"
lacosmic = "1.1.0"
lazy-loader = "0.4"
lineid-plot = "0.6"
locket = "1.0.0"
narwhals = "1.33.0"
ndcube = "2.3.1"
networkx = "3.4.2"
numcodecs = "0.15.1"
numpy = "2.2.4"
packaging = "24.2"
pandas = "2.2.3"
partd = "1.4.2"
patsy = "1.0.1"
pillow = "11.1.0"
pip = "25.0"
plotly = "6.0.1"
pyerfa = "2.0.1.5"
pyparsing = "3.2.0"
pynverse = "0.1.4.6"
python-dateutil = "2.9.0post0"
pytz = "2025.2"
pyyaml = "6.0.2"
reproject = "0.14.1"
scikit-image = "0.25.2"
scikit-learn = "1.6.1"
scipy = "1.15.2"
semantic-version = "2.10.0"
setuptools = "72.1.0"
six = "1.16.0"
spectresc = "1.0.4"
specutils = "1.19.0"
statsmodels = "0.14.4"
threadpoolctl = "3.5.0"
tifffile = "2025.3.30"
toolz = "1.0.0"
tornado = "6.4.2"
tqdm = "4.67.1"
typing-extensions = "4.13.0"
tzdata = "2025.2"
unicodedata2 = "15.1.0"
wheel = "0.45.1"
wrapt = "1.17.2"
yaml = "0.2.5"
zarr = "3.0.6"
zipp = "3.21.0"

# GitHub dependencies
ASPIRED_74in = { git = "https://github.com/LloydLandsberg/ASPIRED_74in.git" }
rascal_fork = { git = "https://github.com/LloydLandsberg/rascal_fork.git" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

