[tool.poetry]
name = "terminally_ASPIRED"
version = "0.1.3"
description = "CLI for spectral reduction for the SAAO 74 inch using ASPIRED backend"
authors = ["Francois Campher, Lloyd Landsberg"]
maintainers = ["Francois Campher"]
license = "MIT"
readme = "README.md"
license-files = ["LICEN[CS]E*"]

[tool.poetry.dependencies]
astroscrappy = "1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.peotry.scripts]
mytool = "terminally-ASPIRED.cli:main"